AvtobuskaStanica/Models/Relation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace AvtobuskaStanica.Models
{
    public class Relation
    {
        public int id { get; set; }
        [Required]
        public string fromDestination { get; set; }
        [Required]
        public  string toDestination { get; set; }
        [Required]
        public int priceOneWay { get; set; }
        [Required]
        public int priceRoundTrip { get; set; }
        [Required]
        public  int capacity { get; set; }
        [Required]
        public string time { get; set; }
        [Required]
        public string company { get; set; }

        
        public  ICollection<Customer> Customers { get; set; }

    }
}

AvtobuskaStanica/Controllers/CustomerController.cs
using AvtobuskaStanica.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AvtobuskaStanica.Controllers
{
    public class CustomerController : Controller
    {

        Customer customer = new Customer();
        Context.ApplicationDbContext db = new Context.ApplicationDbContext();
        
        // GET: Customer
        public ActionResult Index()
        {
            
            return View(db.Customers.ToList());
        }

        // GET: Customer/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Customer/Create
        public ActionResult CreateCustomer()
        {
            return View();
        }

        // POST: Customer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCustomer([Bind(Include = "id,serialNumber,cardNumber,name")] Customer customer)
        {
         
            if (ModelState.IsValid)
            {
                
                //customer.capacity = customer.capacity - 1;
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }

            return View(customer);
        }

        // GET: Customer/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Customer/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Customer/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Customer/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AvtobuskaStanica/Controllers/RelationController.cs
using AvtobuskaStanica.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AvtobuskaStanica.Controllers
{
    public class RelationController : Controller
    {

        Relation rel = new Relation();
        // GET: Relation
        Context.ApplicationDbContext db = new Context.ApplicationDbContext();
         public ActionResult OneRelation()
         {

            return View(rel);
         }
        [AllowAnonymous]
        public ActionResult Index()
        {

            return View(db.Relations.ToList());
        }


        // GET: Relation/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
    
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relation relation = db.Relations.Find(id);
           
            if (relation == null)
            {
                return HttpNotFound();
            }
          
           
           
          
            return View(relation);
        }

        [Authorize(Roles = "Admin,Sales")]
        public ActionResult RelationCustomers(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relation relation = db.Relations.Find(id);
           // relation.Customers = relation.Customers.ToList();
            if (relation == null)
            {
                return HttpNotFound();
            }

            return View(relation);
        }

        // GET: Relation/Create
        [Authorize(Roles = "Admin,Sales")]
        public ActionResult CreateRelation()
        {
            return View();
        }

        // POST: Relation/Create
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult CreateRelation([Bind(Include = "id,fromDestination,toDestination,priceOneWay, priceRoundTrip,capacity,time,company")] Relation relation)
        {
            if (ModelState.IsValid)
            {
                db.Relations.Add(relation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(relation);
        }

        // GET: Relation/Edit/5
        [Authorize(Roles = "Admin, Sales")]
        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relation relation = db.Relations.Find(id);
            if (relation == null)
            {
                return HttpNotFound();
            }
            return View(relation);

        }

        // POST: Relation/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
     
        public ActionResult Edit([Bind(Include = "id,fromDestination,toDestination,priceOneWay, priceRoundTrip,capacity,time,company")] Relation relation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(relation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(relation);
        }

        [AllowAnonymous]
        public ActionResult TicketSale(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relation relation = db.Relations.Find(id);
            if (relation == null)
            {
                return HttpNotFound();
            }
            return View(relation);
        }


   

        // GET: Relation/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relation relation = db.Relations.Find(id);
            if (relation == null)
            {
                return HttpNotFound();
            }
            return View(relation);
        }

        // POST: Relation/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            Relation relation = db.Relations.Find(id);
            db.Relations.Remove(relation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

AvtobuskaStanica/Views/Relation/CreateRelation.cshtml
@model AvtobuskaStanica.Models.Relation

@{
    ViewBag.Title = "Нова Релација";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Додади нова релација</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="margin-left:380px">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.fromDestination,"Од",htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.fromDestination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fromDestination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.toDestination, "До", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.toDestination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.toDestination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.priceOneWay, "Цена еден правец", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.priceOneWay,  new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.priceOneWay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.priceRoundTrip, "Цена повратен билет", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.priceRoundTrip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.priceRoundTrip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.capacity, "Капацитет", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.capacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.capacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.time, "Време", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control", @type = "time" }  })
                @Html.ValidationMessageFor(model => model.time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.company, "Превозник", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.company, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.company, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Додади" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

AvtobuskaStanica/Views/Relation/Delete.cshtml
@model AvtobuskaStanica.Models.Relation

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3 style="text-align:center">Дали сте сигурни дека сакате да ја избришете избраната релација?</h3>

<div class="card" style="width: 350px; margin:auto; text-align:center">
    <img class="card-img-top" src="~/Content/Mercedes-Benz-buses-wallpaper.jpg" width="100%" height="100%">
    <div class="card-body">
        <h5 class="card-title">Детали</h5>
        <div class="card-text">
            <dl class="dl-horizontal">
                <dt>
                    Од
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.fromDestination)
                </dd>

                <dt>
                    До
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.toDestination)
                </dd>

                <dt>
                    Цена еден правец
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.priceOneWay)
                </dd>

                <dt>
                    Цена повратен билет
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.priceRoundTrip)
                </dd>

                <dt>
                    Слободни места
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.capacity)
                </dd>

                <dt>
                    Време
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.time)
                </dd>

                <dt>
                    Превозник
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.company)
                </dd>

            </dl>
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <a href="@Url.Action("Index", "Relation")" class="btn btn-primary">Назад</a>
            <input type="submit" value="Избриши" class="btn btn-danger" />

        </div>
        }
    </div>
</div>

AvtobuskaStanica/Views/Relation/Details.cshtml
@model AvtobuskaStanica.Models.Relation

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="card" style="width: 350px; margin:auto; text-align:center">
    <img class="card-img-top" src="~/Content/Mercedes-Benz-buses-wallpaper.jpg" width="100%" height="100%">
    <div class="card-body">
        <h5 class="card-title">Детали</h5>
        <div class="card-text">
    <dl class="dl-horizontal">
        <dt>
           Од
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fromDestination)
        </dd>

        <dt>
            До
        </dt>

        <dd>
            @Html.DisplayFor(model => model.toDestination)
        </dd>

        <dt>
            Цена еден правец
        </dt>

        <dd>
            @Html.DisplayFor(model => model.priceOneWay)
        </dd>

        <dt>
            Цена повратен билет
        </dt>

        <dd>
            @Html.DisplayFor(model => model.priceRoundTrip)
        </dd>

        <dt>
            Слободни места
        </dt>

        <dd>
            @Html.DisplayFor(model => model.capacity)
        </dd>

        <dt>
            Време
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>

        <dt>
            Превозник
        </dt>

        <dd>
            @Html.DisplayFor(model => model.company)
        </dd>

    </dl>
</div>
        
        <a href="@Url.Action("Index", "Relation")" class="btn btn-primary">Назад</a>
        <a href="@Url.Action("Edit", "Relation",new { id = Model.id })" class="btn btn-success">Измени</a>
    </div>
</div>

AvtobuskaStanica/Views/Relation/Edit.cshtml
@model AvtobuskaStanica.Models.Relation

@{
    ViewBag.Title = "Измени";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align:center">Измени</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="width:350px; margin:auto">
       
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.fromDestination, "Од", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fromDestination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fromDestination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.toDestination, "До", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.toDestination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.toDestination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.priceOneWay, "Цена еден правец", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.priceOneWay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.priceOneWay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.priceRoundTrip, "Цена повратен билет", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.priceRoundTrip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.priceRoundTrip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.capacity, "Капацитет", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.capacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.capacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.time, "Време", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control", @type="" } })
                @Html.ValidationMessageFor(model => model.time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.company, "Превозник", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.company, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.company, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Зачувај" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

AvtobuskaStanica/Views/Relation/Index.cshtml
@model IEnumerable<AvtobuskaStanica.Models.Relation>

@{
    ViewBag.Title = "Возен Ред";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Возен ред</h2>


    @if (User.IsInRole("Sales") || User.IsInRole("Admin"))
    {
        @Html.ActionLink("Додади нова релација", "CreateRelation")
    }
</button>
<br />
<br />
<table class="table">
    <tr>
        <th>
            Од
        </th>
        <th>
            До
        </th>

        <th>
          Цена еден правец
        </th>
        <th>
            Цена повратен билет
        </th>
        <th>
            Поаѓање
        </th>
        <th>
            Превозник
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.fromDestination)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.toDestination)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.priceOneWay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.priceRoundTrip)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.company)
        </td>
        <td>

            @if (User.IsInRole("Sales") || User.IsInRole("Admin"))
            {
                @Html.ActionLink("Измени", "Edit", new { id = item.id }) 
            }

            @if (User.IsInRole("Sales") || User.IsInRole("Admin"))
            {
                @Html.ActionLink("Преглед", "RelationCustomers", new { id = item.id }) 
            }

            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink("Избриши", "Delete", new { id = item.id })
            }
            @Html.ActionLink("Детали", "Details", new { id = item.id }) 

            @Html.ActionLink("Купи билет", "TicketSale", new { id = item.id })



            @*@if (User.IsInRole("Sales") || User.IsInRole("Admin"))
        {
        @Html.ActionLink("Измени", "Edit", new { id = item.id })
        }
        @Html.ActionLink("Детали", "Details", new { id = item.id }) |

        @if (User.IsInRole("Admin"))
        {
            @Html.ActionLink("Избриши", "Delete", new { id = item.id })
        }



        @Html.ActionLink("Купи билет", "TicketSale", new { id = item.id })*@

        </td>
    </tr>
}

</table>

AvtobuskaStanica/Views/Relation/RelationCustomers.cshtml
@model AvtobuskaStanica.Models.Relation

@{
    ViewBag.Title = "RelationCustomers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Преглед по продадени карти за релација</h2>

<div>
  
    <dl class="dl-horizontal">
        <dt>
            Од
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fromDestination)
        </dd>

        <dt>
            До
        </dt>
        @Html.DisplayNameFor(model => model.toDestination)
        <dd>

        </dd>

        <dt>
            Цена еден правец
        </dt>

        <dd>
            @Html.DisplayFor(model => model.priceOneWay)
        </dd>

        <dt>
            Цена повратен билет
        </dt>

        <dd>
            @Html.DisplayFor(model => model.priceRoundTrip)
        </dd>

        <dt>
            Капацитет
        </dt>

        <dd>
            @Html.DisplayFor(model => model.capacity)
        </dd>

        <dt>
            Време
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>

        <dt>
            Превозник
        </dt>

        <dd>
            @Html.DisplayFor(model => model.company)
        </dd>

    </dl>
    <h2>Билети</h2>
    <ol>
        <li>377749932564</li>
        <li>894637289323</li>
        <li>567499322345</li>
    </ol>
</div>
<p> |
    @Html.ActionLink("Назад", "Index")
</p>

AvtobuskaStanica/Views/Relation/TicketSale.cshtml
@model AvtobuskaStanica.Models.Relation

@{
    ViewBag.Title = "TicketSale";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<script>
    function ShowHideDiv() {


        if (document.getElementById("oneWay").checked) {
            var priceField = document.getElementById("price");
            priceField.value = '@Model.priceOneWay';

        } else if (document.getElementById("roundTrip").checked) {
            var priceField = document.getElementById("price");
            priceField.value = '@Model.priceRoundTrip';
        }
    }



</script>



<h2>Купи билет</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)

   

    <div class="form-group">
        @Html.LabelFor(model => model.fromDestination, "Од", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fromDestination, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.fromDestination, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.toDestination, "До", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.toDestination, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.toDestination, "", new { @class = "text-danger" })
        </div>
    </div>

     <div class="col-md-10">
    <div class="form-check">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="optionsRadios" id="oneWay" value="Еден Правец" onclick="ShowHideDiv()">
            Еден правец
        </label>
    </div>
    <div class="form-check">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="optionsRadios" id="roundTrip" value="Повратен билет" onclick="ShowHideDiv()">
            Повратен билет
        </label>
    </div>
    </div>
  

    <div class="form-group">
        <div class="col-md-10">
            <label class="control-label col-md-2" for="readOnlyInput">Цена</label>
            <input class="form-control" id="price" type="text" readonly="">
        </div>
    </div>

    <div class="col-md-10">
    <label for="start">Избери датум:</label>

    <input type="date" id="start" name="trip-start"
           value="2020-01-01">
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.time, "Време", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.time, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.company, "Превозник", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.company, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.company, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <a href="@Url.Action("CreateCustomer", "Customer",new {Relation_id=Model.id})" class="btn btn-primary">Купи</a>
        </div>
    </div>
</div>

   
  
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>