AvtobuskaStanica/Controllers/PageDownController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AvtobuskaStanica.Controllers
{
    public class PageDownController : Controller
    {
        // GET: PageDown
        [AllowAnonymous]
        public ActionResult AboutUs()
        {
            return View();
        }

        // GET: PageDown/Details/5
        [AllowAnonymous]
        public ActionResult Gallery()
        {
            return View();
        }

        // GET: PageDown/Create
        [AllowAnonymous]
        public ActionResult Note()
        {
            return View();
        }

        // POST: PageDown/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: PageDown/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PageDown/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: PageDown/Delete/5
        [AllowAnonymous]
        public ActionResult ContactPage()
        {
            return View();
        }
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PageDown/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AvtobuskaStanica/Controllers/RelationController.cs
using AvtobuskaStanica.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AvtobuskaStanica.Controllers
{
    public class RelationController : Controller
    {

        Relation rel = new Relation();
        // GET: Relation
        Context.ApplicationDbContext db = new Context.ApplicationDbContext();
         public ActionResult OneRelation()
         {

            return View(rel);
         }
        [AllowAnonymous]
        public ActionResult Index()
        {

            return View(db.Relations.ToList());
        }


        // GET: Relation/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
    
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relation relation = db.Relations.Find(id);
           
            if (relation == null)
            {
                return HttpNotFound();
            }
          
           
           
          
            return View(relation);
        }

        [Authorize(Roles = "Admin,Sales")]
        public ActionResult RelationCustomers(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relation relation = db.Relations.Find(id);
           // relation.Customers = relation.Customers.ToList();
            if (relation == null)
            {
                return HttpNotFound();
            }

            return View(relation);
        }

        // GET: Relation/Create
        [Authorize(Roles = "Admin,Sales")]
        public ActionResult CreateRelation()
        {
            return View();
        }

        // POST: Relation/Create
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult CreateRelation([Bind(Include = "id,fromDestination,toDestination,priceOneWay, priceRoundTrip,capacity,time,company")] Relation relation)
        {
            if (ModelState.IsValid)
            {
                db.Relations.Add(relation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(relation);
        }

        // GET: Relation/Edit/5
        [Authorize(Roles = "Admin, Sales")]
        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relation relation = db.Relations.Find(id);
            if (relation == null)
            {
                return HttpNotFound();
            }
            return View(relation);

        }

        // POST: Relation/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
     
        public ActionResult Edit([Bind(Include = "id,fromDestination,toDestination,priceOneWay, priceRoundTrip,capacity,time,company")] Relation relation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(relation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(relation);
        }

        [AllowAnonymous]
        public ActionResult TicketSale(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relation relation = db.Relations.Find(id);
            if (relation == null)
            {
                return HttpNotFound();
            }
            return View(relation);
        }


   

        // GET: Relation/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relation relation = db.Relations.Find(id);
            if (relation == null)
            {
                return HttpNotFound();
            }
            return View(relation);
        }

        // POST: Relation/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            Relation relation = db.Relations.Find(id);
            db.Relations.Remove(relation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

AvtobuskaStanica/Controllers/RoleController.cs
using AvtobuskaStanica.Models;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AvtobuskaStanica.Controllers
{
   
    public class RoleController : Controller
    {
        private ApplicationRoleManager _roleManager;

        public RoleController()
        {
        }

        public RoleController(ApplicationRoleManager roleManager)
        {
            RoleManager = roleManager;
        }

        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        // GET: Role
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            List<RoleViewModel> list = new List<RoleViewModel>();
            foreach(var role in RoleManager.Roles)
            {
                list.Add(new RoleViewModel(role));
            }
            return View(list);
        }

       
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel model)
        {
            var role = new ApplicationRole() { Name = model.name };
            await RoleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            return View(new RoleViewModel(role));
        }
        [HttpPost]
        public async Task<ActionResult> Edit(RoleViewModel model)
        {
            var role = new ApplicationRole() { Id = model.id, Name = model.name };
            await RoleManager.UpdateAsync(role);
            return RedirectToAction("Index");
        } 


        public async Task<ActionResult> Details(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            return View(new RoleViewModel(role));
        }

        public async Task<ActionResult> Delete(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            return View(new RoleViewModel(role));
        }
        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            await RoleManager.DeleteAsync(role);
            return RedirectToAction("Index");
        }
    }
}

AvtobuskaStanica/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <p class="nav-link" style="color:forestgreen !important;">@Html.ActionLink("Почетна", "Index", "Home")</p>
                </li>
                <li class="nav-item">
                    <p class="nav-link" style="color:forestgreen !important;">@Html.ActionLink("Возен Ред", "Index", "Relation")</p>
                </li>
                <li class="nav-item">
                    <p class="nav-link" style="color:forestgreen !important;">@Html.ActionLink("Контакт", "ContactPage", "PageDown")</p>
                </li>
                <li class="nav-item">
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin"))
                        {
                            <p class="nav-link" style="color:forestgreen !important;">@Html.ActionLink("Додади улога", "Index", "Role")</p>
                        }
                    }
                </li>
                <li class="nav-item">
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin"))
                        {
                            <p class="nav-link" style="color:forestgreen !important;">@Html.ActionLink("Назначи на улога", "AddUserToRole", "Account")</p>
                        }
                    }
                </li>
            </ul>

            @if (Request.IsAuthenticated)
            {
                using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                {
                    @Html.AntiForgeryToken()

                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                        </li>
                        <li><a style="margin-left:10px" href="javascript:document.getElementById('logoutForm').submit()">Одјави се</a></li>
                    </ul>
                }
            }
            else
            {
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Регистрирај се", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                    <li style="margin-left:10px">@Html.ActionLink("Најави се", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                </ul>
            }
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>